apiVersion: v1
kind: Service
metadata:
  name: ${parameters.APP_NAME}
  namespace: ${parameters.NAMESPACE}
spec:
  type: ${parameters.SERVICE_TYPE}
  selector:
    app: ${parameters.APP_NAME}
  ports:
    - name: http
      port: ${parameters.SERVICE_PORT}
      targetPort: http
      protocol: TCP
