# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ${APP_NAME}
# spec:
#   replicas: ${REPLICAS_DEV}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: ${REPLICAS}
